services:
  db:
    image: postgres:14-alpine
    shm_size: 256mb
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ./postgres14:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

  redis:
    image: redis:7-alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ./redis:/data
#   es:
#     image: ghcr.io/nzws/elasticsearch-sudachi:latest
#     environment:
#       - 'ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.enforce.bootstrap.checks=true'
#       - 'xpack.license.self_generated.type=basic'
#       - 'xpack.security.enabled=false'
#       - 'xpack.watcher.enabled=false'
#       - 'xpack.graph.enabled=false'
#       - 'xpack.ml.enabled=false'
#       - 'bootstrap.memory_lock=true'
#       - 'cluster.name=es-mastodon'
#       - 'discovery.type=single-node'
#       - 'thread_pool.write.queue_size=1000'
#     expose:
#       - 9200
#     ports:
#       - '9200:9200'
#     healthcheck:
#       test:
#         [
#           'CMD-SHELL',
#           'curl --silent --fail localhost:9200/_cluster/health || exit 1',
#         ]
#     volumes:
#       - ./elasticsearch:/usr/share/elasticsearch/data
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#       nofile:
#         soft: 65536
#         hard: 65536
#  libretranslate:
#    image: libretranslate/libretranslate:v1.2.9
#    ports:
#      - 5000:5000
#    networks:
#      - internal_network
